export const metadata = {
  title: "RUMAH MADINAH CAKE & BAKERY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
